### PR TITLE
Support for erlang otp 19

### PR DESCRIPTION
**Pull request by ludwikbukowski**

### CODE REVIEW

**Comment by arkgil** [comment]
Has escalus API been changed in version 3.0.0? If that is a case, we should probably update scenarios.

**Comment by ludwikbukowski** [comment]
good catch! It shouldn't but I will check

**Comment by kklocek** [comment]
Any updates on that @ludwikbukowski ?

**Comment by ludwikbukowski** [comment]
only one thing that breaks backward compability in Escalus is this issue https://github.com/esl/escalus/pull/117 . I think it does not affect the scenarios

**Pull request merged**
